#FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime
#FROM 763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/pytorch-trcomp-training:1.12.0-gpu-py38-cu113-ubuntu20.04-sagemaker
FROM ghcr.io/allenai/pytorch:1.12.1-cuda11.3-python3.9-v1.2.0
ENV PATH="/opt/ml/code:${PATH}"

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install --assume-yes apt-utils -y

RUN apt update
RUN echo "Y"|apt install vim
RUN apt install wget git -y
RUN apt install libgl1-mesa-glx -y
RUN pip install opencv-python-headless

#RUN echo "Y"|apt-get install libglib2.0-dev
#RUN echo "Y"|apt-get install libxext-dev
#RUN echo "Y"|apt-get install libxrender1
#RUN pip install markupsafe==2.0.1
#RUN echo "Y"|apt-get install gcc-7 && echo "Y"|apt-get install g++-7
#RUN pip install cutlass

RUN mkdir -p /opt/ml/code

# install the SageMaker Training Toolkit 
RUN pip3 install sagemaker-training

COPY train.py /opt/ml/code/
COPY ./sd_code/ /opt/ml/code/

RUN pip install -r /opt/ml/code/extensions/sd_dreambooth_extension/requirements.txt
# this environment variable is used by the SageMaker training toolkit to determine our program entry point
ENV SAGEMAKER_PROGRAM /opt/ml/code/sd_dreambooth_extension/dreambooth/train_dreambooth.py

#RUN python3 -m venv /opt/ml/code/venv
#RUN echo "Y"|apt install build-essential

#RUN . /opt/ml/code/venv/bin/activate
#RUN cd /opt/ml/code && pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
RUN export TORCH_CUDA_ARCH_LIST="7.5 8.0 8.6" && export FORCE_CUDA="1" && pip install ninja triton==2.0.0.dev20221120 && git clone https://github.com/xieyongliang/xformers.git /opt/ml/code/repositories/xformers && cd /opt/ml/code/repositories/xformers && git submodule update --init --recursive && pip install -r requirements.txt && pip install -e . 

ENTRYPOINT []
